### ISSUE TITLE
Grader fails on all tests, seems like type info is getting lost, isfinite datatype check can't be applied.

### ISSUE THREAD

**Issue by brookman1** [Anwarvic/Mathematics-for-Machine-Learning-Specialization#4]
The graded function specifically returns:
```python
    return covariance_matrix.astype('float64')
```
not sure how the grader changes the type, this is failing for all 4 tests.
```
======================================================================
ERROR: test_cov (week1_tests.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autograde_pnpmxbbt/week1_tests.py", line 32, in test_cov
    np.testing.assert_allclose(result, cov(X))
  File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1533, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 794, in assert_array_compare
    val = comparison(x, y)
  File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1528, in compare
    equal_nan=equal_nan)
  File "<__array_function__ internals>", line 6, in isclose
  File "/opt/conda/lib/python3.7/site-packages/numpy/core/numeric.py", line 2257, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

It appears to fail for functions defined in this notebook [here](https://notebooks.githubusercontent.com/view/ipynb?browser=unknown_browser&color_mode=auto&commit=36d21bbe11462d5b377625fb5b7c857d97094d6b&device=unknown_device&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f74756e74756e77696e6b69632f6d6c696f742f333664323162626531313436326435623337373632356662356237633835376439373039346436622f7765656b312e6970796e62&logged_in=false&nwo=tuntunwinkic%2Fmliot&path=week1.ipynb&platform=unknown_platform&repository_id=234924583&repository_type=Repository&version=0) as well.

**Comment by brookman1** [comment]
As it turns out the submission doesn't work until notebook is exported as .ipynb and then imported back in for grading.
